/**
 * triggerWorkflowWebhook — the inbound webhook trigger.
 *
 * Exposed to Hasura's unauthorized `public` role, so an external system can
 * start a run with no user session. There is therefore no org role to check;
 * authentication is the per-trigger secret, which:
 *   * is generated by Postgres (24 random bytes), never chosen by a client,
 *   * is excluded from every GraphQL select permission, so it cannot be read
 *     out of the API even by an owner — only the getWebhookEndpoint Action
 *     hands it out, and only to owners,
 *   * is compared in constant time.
 *
 * Failures are deliberately indistinguishable ("unknown trigger or bad secret"),
 * so the endpoint cannot be used to enumerate trigger ids.
 *
 * The run still goes through start_workflow_run(), so an inbound webhook is
 * subject to exactly the same quota rules as a human pressing Run.
 */
import { after } from 'next/server';
import { ActionError, secretsMatch } from '../auth';
import { adminGraphql } from '../hasura';
import { runInBackground } from '../engine/runner';
import { startRun } from '../engine/store';
import type { Json } from '../engine/types';
import { countStepRuns, requireUuid } from './shared';
import type { TriggerRunOutput } from './triggerWorkflowRun';

export interface TriggerWebhookInput {
  trigger_id: string;
  secret: string;
  payload?: Json;
}

const OPAQUE = 'Unknown trigger, or the secret is incorrect.';

// The Caller is intentionally unused: this action authenticates with the
// trigger's secret, not with a user session, so it takes no second parameter.
export async function triggerWorkflowWebhook(
  input: TriggerWebhookInput,
): Promise<TriggerRunOutput> {
  const triggerId = requireUuid(input.trigger_id, 'trigger_id');
  if (typeof input.secret !== 'string' || input.secret.length === 0) {
    throw new ActionError('UNAUTHENTICATED', OPAQUE, 401);
  }

  const data = await adminGraphql<{
    workflow_triggers_by_pk: {
      id: string;
      type: string;
      secret: string;
      is_enabled: boolean;
      workflow: { id: string; org_id: string; is_active: boolean };
    } | null;
  }>(
    `query LoadWebhookTrigger($id: uuid!) {
       workflow_triggers_by_pk(id: $id) {
         id
         type
         secret
         is_enabled
         workflow { id org_id is_active }
       }
     }`,
    { id: triggerId },
  );

  const trigger = data.workflow_triggers_by_pk;
  if (!trigger || trigger.type !== 'webhook' || !secretsMatch(input.secret, trigger.secret)) {
    throw new ActionError('UNAUTHENTICATED', OPAQUE, 401);
  }
  if (!trigger.is_enabled) {
    throw new ActionError('TRIGGER_DISABLED', 'This webhook trigger is disabled.', 409);
  }

  const run = await startRun({
    workflowId: trigger.workflow.id,
    userId: null,
    triggerType: 'webhook',
    payload: input.payload ?? {},
    // No user session exists, so there is no membership to check. The secret is
    // the credential; quota and workflow state are still enforced.
    requireRole: false,
  });

  await adminGraphql(
    `mutation MarkTriggerFired($id: uuid!, $at: timestamptz!) {
       update_workflow_triggers_by_pk(pk_columns: { id: $id }, _set: { last_fired_at: $at }) { id }
     }`,
    { id: triggerId, at: new Date().toISOString() },
  );

  const stepCount = await countStepRuns(run.id);
  after(() => runInBackground(run.id));

  return {
    workflow_run_id: run.id,
    workflow_id: trigger.workflow.id,
    status: 'running',
    step_count: stepCount,
  };
}
